### ISSUE TITLE
Bootstrap Material

### ISSUE THREAD

**Issue by nadeemja** [bootcards/bootcards#36]
Hi,

Great project! So happy I stumbled over it.

Do you think bootcards would work well with Boostrap Material?
http://fezvrasta.github.io/bootstrap-material-design/

Any immediate concerns? 

Thanks in advance :)

**Comment by ashugit** [comment]
Any update on bootstrap-material-design with bootcards, if this works smoothly now ?
@markleusink if you have any suggestion of using material theme with bootcards ?

**Comment by markleusink** [comment]
Sorry, but no update. Bootcards still uses Holo Light for Android. It might work, but I haven't tested it. Feel free to do that.
