### ISSUE TITLE
Documentation Request... bootcards.init()

### ISSUE THREAD

**Issue by RHOPKINS13** [bootcards/bootcards#41]
Am I missing something? I spent forever trying to figure out why my sliding sidebar wasn't working, and finally got it to work after figuring out that I needed to initialize bootcards first using bootcards.init(). I can't find anything in the documentation about this, I found it at the bottom of the demo. Is this documented anywhere?

**Comment by markleusink** [comment]
Good call. The bootcards.init() was in the sample files (in the samples folder of the repo), but not in the docs. I've added a paragraph in the 'getting started' on the homepage for it.
