### ISSUE TITLE
List > Arrow Render Issue

### ISSUE THREAD

**Issue by westy92** [bootcards/bootcards#42]
The ">" arrow in a list does not always render correctly.

![image](https://cloud.githubusercontent.com/assets/290167/7448119/f048e8ac-f1d6-11e4-94fa-b36f1bd363d7.png)

It appears to be rendering the content as more than one character.

        a.list-group-item:before {
            font-family:FontAwesome;
            content:'ï”';
            ...
        }

Note: I am using Chrome 42.0.2311.90 m on Windows 7 Pro.

**Comment by jackherbert** [comment]
Looks like it might be an encoding issue. Is your encoding set to UTF-8?

```<meta charset="utf-8">```

**Comment by whitemx** [comment]
I've found that the issue goes away when using the non minified CSS. So it's something to do with the minifying process that's causing it I think.

**Comment by westy92** [comment]
The screenshot is from an example on the [http://bootcards.org/site/docs.html](http://bootcards.org/site/docs.html) page, so it does have the encoding set: `<meta charset="utf-8">`.
