### ISSUE TITLE
Replace original Sass with libSass

### ISSUE THREAD

**Issue by RubenCordeiro** [bootcards/bootcards#46]
Hello,

I want to start off with a big thank you to the contributors of this library. I've used Bootcards in a recent project and it is a wonder to work with.

Have you thought about replacing the ruby implementation of Sass with libSass? (http://sass-lang.com/libsass)

There is great library that provides bindings for Node.js to libsass: Node-sass (https://github.com/sass/node-sass)

In my opinion, this would be beneficial, since an installation of Ruby would no longer be required and libSass is up to 4000% faster than the ruby distribution.

**Comment by markleusink** [comment]
Thanks for the tip! Hadn't heard of that one before.
