### ISSUE TITLE
starter template not working

### ISSUE THREAD

**Issue by vishals321** [bootcards/bootcards#48]
even starter is not working and also examples in docs. I have checked all things.

**Comment by markleusink** [comment]
Just tested on my local machine and it seems to work just fine. I have [NodeJS](https://nodejs.org/), [Bower](http://bower.io/) and [http-server](https://www.npmjs.com/package/http-server) (basic HTTP server running on Node) installed, so I do:

    mkdir bootcards
    cd bootcards
    bower install bootcards
    http-server -o

Then in the browser I open

    http://127.0.0.1:8080/bower_components/bootcards/samples/starter-template.html

There's a theme switcher on that sample page that you can use to check out the iOS, Android and desktop styles.

**Comment by Thessalie** [comment]
seems to work fine here too, installed day before yesterday

2015-06-20 11:22 GMT+02:00 Mark Leusink <notifications@github.com>:

**Comment by vishals321** [comment]
cant i use it on shared hosting?

**Comment by markleusink** [comment]
Sure you can. You can either use cdnjs.com to serve up Bootcards (links on bootcards.org) or serve it yourself.
