### ISSUE TITLE
Styles missing from repo?

### ISSUE THREAD

**Issue by elado** [bootcards/bootcards#52]
With current `dist` code in master, bootcards-dekstop.css renders: 
![screen shot 2015-07-13 at 2 53 53 pm](https://cloud.githubusercontent.com/assets/51488/8661778/02b3d054-296f-11e5-8745-cccb90825417.png)

Several styles that exist on the demo page (http://demo.bootcards.org/contacts), like

![screen shot 2015-07-13 at 2 48 26 pm](https://cloud.githubusercontent.com/assets/51488/8661733/8c0a8f92-296e-11e5-9f8f-0627811b499e.png)

are missing.

Am I missing something?

**Comment by markleusink** [comment]
Just tested that starting from scratch:
* create folder, run `bower init`
* do a `bower install bootcards`
* start a HTTP server using `http-server -o` (I'm using [this](https://github.com/indexzero/http-server) one)
* open the starter template at `localhost:8080/bower_components/bootcards/samples/starter-template.html`

By default that has the iOS styles and looks fine. I then disabled the `bootcards-ios.min.css` stylesheet and un-commented the desktop one. Still looks fine (see below). Remember to lood Bootstrap (3.3+), Font Awesome and one of the Bootcards CSS files from the `dist` folder.

![screenshot 2015-07-14 08 26 15](https://cloud.githubusercontent.com/assets/1773707/8667670/c8e45300-2a02-11e5-8ab8-fbe761aaeea2.png)

**Comment by elado** [comment]
My bad. I had a custom bootstrap build, and realized that the .min.css in the `cdnjs.cloudflare.com` source contains bootstrap in it. So the styles I was referring were in Bootstrap.
Thanks!
