### ISSUE TITLE
Integrating Bootcards breaks existing forms

### ISSUE THREAD

**Issue by zephod** [bootcards/bootcards#60]
Hi guys,
I've dropped BootCards into an existing project and I keep discovering glitches where the additional CSS interferes with existing elements. eg:

https://github.com/bootcards/bootcards/blob/master/src/css/bootcards.scss#L396

I assumed that BootCards would carefully namespace all of its custom CSS. Am I mistaken? What strategy do you recommend here? I can either fork BootCards or probably try to rebuild my site from scratch with the new code.

**Comment by jackherbert** [comment]
Unfortunately, Bootcards currently relies on some specific markup structure like this – it was intended to avoid a sea of custom classnames – but I agree that lines like this are particularly obtrusive.

Have you tried a version of bootcards.scss with the problematic line(s) removed?

**Comment by zephod** [comment]
Yes I see. The issue is that I can't identify which lines are problematic until a customer emails me to complain about a glitch. I maintain five Bootstrap+WordPress sites, all with custom designs by external designers. We run the system, the customer supplies the design. Unless I want to go through everything (five times) to QA it in a variety of browsers -- I can't permit lines like:

    .table > tfoot > tr > td:first-child {
	padding-left: 15px;
    }

Because I've no idea what that will break. But it's bound to break something... it depends what each site's designer has built.

I think my options are:
* Fork bootcards, forcibly namespacing everything (expensive), so I can selectively include it
* Wait for Bootstrap 4 (slow) and migrate and QA (expensive)
* Just rewrite the functionality I need as required (arrrgh)

Anyway thanks for looking at this.

**Comment by jackherbert** [comment]
I hate to say it, but you might be best off forking Bootcards. We have other projects that rely on a few of these quirks, and a new version isn't imminent

Sorry I can't be more help!

**Comment by zephod** [comment]
No worries. Thanks!
